# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "public_network", ip: "10.1.10.55"
  config.vm.provision :shell, :path => "bootstrap.sh"
end
